#!/usr/bin/env zsh
unnamed_module() {
  # load modules
  autoload fox-fr
  autoload zmkfifo
  autoload zrm
  # continuous read from output FIFO
  zkreen() {
    zkreen_terminate=0
    zkreen_target="$@[1]"
    while true; do
      fox-fr $zkreen_target
      sleep 0.1
      if [ $zkreen_terminate = 1 ]; then
        break
      fi
    done
  }
  # write $zomgdelwrite to FIFO & unset, if not empty
  zdelomgprompt() {
    zdelomgprompt_target="$@[1]"
    zomgdel=0
    unset zomgdelwrite
    while true; do
      if [ ! -z "$zomgdelwrite" ]; then
        printf "%s""$zomgdelwrite" > "$zdelomgprompt_target"
        unset zomgdelwrite
      fi
      if [ $zomgdel != 0 ]; then
        break
      fi
    done
  }
  # Command execution daemon
  zlmexec() {
    zlmexec_target="$@[1]"
    zlmexec_term=0
    while true; do
      zsh <<EOF
$(fox-fr $zlmexec_target)
EOF
      if [ $zlmexec_term != 0 ]; then
        break
      fi
    done
  }
  # Setup I/O
  zomgdel_io() {
  }
  # Prompt handler
  zlmprompt() {
  }
}
