#!/usr/bin/env zsh
zterm() {
  autoload libmiscinit
  libmiscinit
  autoload zstat
  autoload ctext
  autoload ztput
  autoload isfile
  autoload fox-fr
  autoload zmkfifo
  autoload zrm
  autoload nrandom
  zmodload zsh/zpty
  autoload trandom
  ## env setup
  if [ -d "/tmp" ]; then
    zterm_working_dir="/tmp"
  else
    zterm_working_dir="$HOME"
  fi
  pseudoterm_name="$(trandom)" &> /dev/null
  zpty -b "$pseudoterm_name" "zsh --login -i"
  while zpty -r "$pseudoterm_name"; do
    sleep 0.1
  done
  zterm_first_loop=1
  # username
  if [ -z "$USER" ]; then
    USER=unknown
  fi
  # hostname
  if [ -z "$HOSTNAME" ]; then
    if isfile /etc/hostname &> /dev/null; then
      HOSTNAME="$(fox-fr /etc/hostname)"
    else
      HOSTNAME=localhost
    fi
  fi
  # ztermrc
  if isfile ""$HOME"/.ztermrc" &> /dev/null; then
    source ""$HOME"/.ztermrc"
  fi
  # hacky newline printer for clear workaround
  zterm_newlines() {
    print; print; print; print; print; print; print; print; print; print
  }
  ## main loop
  while true; do
    # set return to 0 if empty
    [ -z "$zterm_return_val" ] && zterm_return_val=0
    # U.I printout
    while zpty -r "$pseudoterm_name"; do
      sleep 0.1
    done
    if [ ! "$zterm_first_loop" = 1 ]; then
      zterm_return_val=$(fox-fr "$zterm_working_dir"/.zterm_return_"$zterm_return_name")
      until ! isfile "$zterm_working_dir"/.zterm_return_"$zterm_return_name" &> /dev/null; do
        zrm "$zterm_working_dir"/.zterm_return_"$zterm_return_name" &> /dev/null
      done
    else
      zterm_first_loop=0
    fi
    print
    print -n ""$(ztput bold)""$(ctext blue)""$USER""$(ztput dim)""$(ctext magenta)"@""$(ctext reset)"$(ztput bold)""$(ctext blue)""$HOSTNAME" "$(ctext reset)""$(ztput dim)""$(ctext cyan)""$(print -n "$(pwd)")" "$(if [ $zterm_return_val = 0 ]; then ctext green; else ctext reset; ctext red; fi)"> "$(ctext reset)""
    # read user input into variable
    zterm_read=$(read -e " ")
    if [ ! -z "$zterm_read" ]; then
      # hacky clear workaround
      if [ "$zterm_read" = 'clear' ]; then
        zterm_newline_spammer=150
        until [ "$zterm_newline_spammer" = 0 ]; do
          zterm_newlines; zterm_newlines; zterm_newlines; zterm_newlines; zterm_newlines; zterm_newlines; zterm_newlines; zterm_newlines; zterm_newlines; zterm_newlines
          zterm_newline_spammer=$((zterm_newline_spammer-10))
        done
        zterm_return_val=0
      # correctly handle `exit` and `logout`
      elif [ "$zterm_read" = 'exit' ] || [ "$zterm_read" = 'logout' ]; then
        break
      else
        # standard execution with zsh
        zterm_return_name=$(trandom) &> /dev/null
        zpty -w "$pseudoterm_name" ""$zterm_read""$'\n'"echo $? > "$zterm_working_dir"/.zterm_return_"$zterm_return_name""
      fi
    fi
  done
  # return 0 upon `exit` or `logout`
  return 0
}
