#!/usr/bin/env zsh
blep() {
  #load modules
  autoload fox
  autoload getstrln
  autoload ztput
  #fail printout
  blep_fail() {
    print "Usage: print \"some text\" | blep arg1"
  }
  #fetch user input
  unset BLEPREADIN
  if [ -z "$zBLEPWAITINDEF" ] || [ "$zBLEPWAITINDEF" = 0 ]; then
    export zFOXT=3
  else
    unset zFOXT
    unset zBLEPWAITINDEF
  fi
  BLEPREADIN="$(fox)"
  BLEPREADINTEST=${BLEPREADIN: :5}
  if [ "$BLEPREADINTEST" = "error" ]; then
    blep_fail
    return 1
  fi
  if [ -z "$1" ]; then
    blep_fail
    return 1
  else
    BLEPARG="$1"
  fi
  # default return value to 1
  BLEPRET=1
  # fetch length of user input
  BLEPARGLN="$(getstrln "$BLEPARG")"
  # read user input one line at a time
  IFS=$'\n'
  for blep_readin_divided in $=BLEPREADIN; do
    blep_readin_preserve="$blep_readin_divided"
    # check input against given pattern match
    while true; do
      MATCHFOUND=0
      while IFS= noglob read -r -k$BLEPARGLN -d '' -u0 BLEPOUT; do
        if [ "$BLEPARG" = "$BLEPOUT" ]; then
          MATCHFOUND=1
          #set return value to 0 if match found
          BLEPRET=0
          break
        fi
      done < <(noglob printf '%s' "$blep_readin_divided")
      blep_readin_divided=${blep_readin_divided:1}
      # break loop if match found, or if no remaining lines to check
      if [ -z "$blep_readin_divided" ]; then
        break
      fi
      if [ "$MATCHFOUND" = 1 ]; then
        break
      fi
    done
    # if match found, highlight
    if [ "$MATCHFOUND" = 1 ]; then
      if [ -z "$zBLEPNOHIGHLIGHT" ]; then
        BLEPREADINSWAP=""$(ztput 6)""$BLEPARG""$(ztput reset)""
        blep_readin_preserve=${blep_readin_preserve//"$BLEPARG"/"$BLEPREADINSWAP"}
        noglob printf '%s\n' "$blep_readin_preserve"
      else
        noglob printf '%s\n' "$blep_readin_preserve"
      fi
    fi
  done
  unset IFS
  # return
  return $BLEPRET
}
