#!/usr/bin/env zsh
chexd() {
  #load modules
  autoload fox
  #fail printout
  chexd_fail() {
    print "Usage - hexd /path/to/file | chexd"
  }
  #fetch user input
  if [ -z "$zCHEXDWAITINDEF" ] || [ "$zCHEXDWAITINDEF" = 0 ]; then
    export zFOXT=33
  else
    unset zFOXT
    unset zCHEXDWAITINDEF
  fi
  CHEXDIN="$(fox)"
  CHEXDINTEST="${CHEXDIN: :5}"
  if [ "$CHEXDINTEST" = "error" ]; then
    chexd_fail
    return 1
  fi
  #create zero vars
  unset ZERO4096
  ZERO4096COUNT=0
  until [ "$ZERO4096COUNT" -eq 4096 ]; do
    if [ -z "$ZERO4096" ]; then
      ZERO4096="0"
    else
      ZERO4096=""$ZERO4096"0"
    fi
    ZERO4096COUNT=$((ZERO4096COUNT+1))
  done
  ZERO3172=${ZERO4096: :3172}
  ZERO2048=${ZERO4096: :2048}
  ZERO1024=${ZERO2048: :1024}
  ZERO512=${ZERO1024: :512}
  ZERO256=${ZERO512: :256}
  ZERO128=${ZERO256: :128}
  ZERO64=${ZERO128: :64}
  ZERO60=${ZERO64: :60}
  ZERO32=${ZERO64: :32}
  ZERO16=${ZERO32: :16}
  ZERO8=${ZERO16: :8}
  ZERO6=${ZERO8: :6}
  ZERO4=${ZERO6: :4}
  ZERO2=${ZERO4: :2}
  CHEXDIN=${CHEXDIN//"$ZERO4096"/'@'}
  CHEXDIN=${CHEXDIN//"$ZERO3172"/';'}
  CHEXDIN=${CHEXDIN//"$ZERO2048"/'#'}
  CHEXDIN=${CHEXDIN//"$ZERO1024"/'$'}
  CHEXDIN=${CHEXDIN//"$ZERO512"/'_'}
  CHEXDIN=${CHEXDIN//"$ZERO256"/'&'}
  CHEXDIN=${CHEXDIN//"$ZERO128"/'!'}
  CHEXDIN=${CHEXDIN//"$ZERO64"/'?'}
  CHEXDIN=${CHEXDIN//"$ZERO60"/':'}
  CHEXDIN=${CHEXDIN//"$ZERO32"/'<'}
  CHEXDIN=${CHEXDIN//"$ZERO16"/'>'}
  CHEXDIN=${CHEXDIN//"$ZERO8"/')'}
  CHEXDIN=${CHEXDIN//"$ZERO6"/'('}
  CHEXDIN=${CHEXDIN//"$ZERO4"/'{'}
  CHEXDIN=${CHEXDIN//"$ZERO2"/'}'}
  noglob printf '%s' "$CHEXDIN"
  return 0
}
