#!/usr/bin/env zsh
ctext() {
  if [ "$1" = black ]; then
    ztput 0
  fi
  if [ "$1" = red ]; then
    ztput 1
  fi
  if [ "$1" = green ]; then
    ztput 2
  fi
  if [ "$1" = yellow ]; then
    ztput 3
  fi
  if [ "$1" = blue ]; then
    ztput 4
  fi
  if [ "$1" = magenta ]; then
    ztput 5
  fi
  if [ "$1" = cyan ]; then
    ztput 6
  fi
  if [ "$1" = white ]; then
    ztput 7
  fi
  if [ "$1" = dblack ]; then
    ztput setab 0
  fi
  if [ "$1" = dred ]; then
    ztput setab 1
  fi
  if [ "$1" = dgreen ]; then
    ztput setab 2
  fi
  if [ "$1" = dyellow ]; then
    ztput setab 3
  fi
  if [ "$1" = dblue ]; then
    ztput setab 4
  fi
  if [ "$1" = dmagenta ]; then
    ztput setab 5
  fi
  if [ "$1" = dcyan ]; then
    ztput setab 6
  fi
  if [ "$1" = dwhite ]; then
    ztput setab 7
  fi
  if [ "$1" = reset ]; then
    ztput reset
  fi
  if [ "$2" = std ]; then
    echo "${@:3}"
    ztput reset
  fi
  if [ "$2" = nnl ]; then
    echo -n "${@:3}"
    ztput reset
  fi
  if [ "$2" = std,bold ]; then
    ztput bold
    echo "${@:3}"
    ztput reset
  fi
  if [ "$2" = nnl,bold ]; then
    ztput bold
    echo -n "${@:3}"
    ztput reset
  fi
  if [ "$2" = std,dim ]; then
    ztput dim
    echo "${@:3}"
    ztput reset
  fi
  if [ "$2" = nnl,dim ]; then
    ztput dim
    echo -n "${@:3}"
    ztput reset
  fi
  if [ "$2" = std,nres ]; then
    echo "${@:3}"
  fi
  if [ "$2" = nnl,nres ]; then
    echo -n "${@:3}"
  fi
  if [ "$2" = std,bold,nres ]; then
    ztput bold
    echo "${@:3}"
  fi
  if [ "$2" = nnl,bold,nres ]; then
    ztput bold
    echo -n "${@:3}"
  fi
  if [ "$2" = std,dim,nres ]; then
    ztput dim
    echo "${@:3}"
  fi
  if [ "$2" = nnl,dim,nres ]; then
    ztput dim
    echo -n "${@:3}"
  fi
  if [ "$2" = chkmrk ]; then
    ztput bold
    echo -e "\xE2\x9C\x94"
    ztput reset
  fi
  if [ "$2" = xmrk ]; then
    ztput bold
    echo "X"
    ztput reset
  fi
  if [ "$2" = grin ]; then
    ztput bold
    echo "😀"
    ztput reset
  fi
  if [ "$2" = smile ]; then
    ztput bold
    echo "☺"
    ztput reset
  fi
  if [ "$2" = glss ]; then
    ztput bold
    echo "😎"
    ztput reset
  fi
  if [ "$2" = frown ]; then
    ztput bold
    echo "☹"
    ztput reset
  fi
  if [ "$2" = horrif ]; then
    ztput bold
    echo "😱"
    ztput reset
  fi
  if [ "$2" = dead ]; then
    ztput bold
    echo "☠"
    ztput reset
  fi
  return 0
}
