#!/usr/bin/env zsh

findlibmisc() {
  autoload blep
  find_libmisc_fpath_read="$(echo -n "$fpath")"
  libmisc_found=0
  IFS=$' '
  for fpath_items in $=find_libmisc_fpath_read; do
    if print $fpath_items | blep 'libmisc.zwc' &> /dev/null; then
      print $fpath_items
      libmisc_found=1
      break
    fi
  done
  unset IFS
  return "$libmisc_found"
}
