#!/usr/bin/env zsh
hexud() {
  #load modules
  autoload fox
  autoload fox-fr
  autoload isfile
  #failure printout
  hexud_fail() {
    print "Usage: print -n <hex> | hexud"
    print "       hexud <hex>"
    print "       hexud /path/to/file"
    print "       print -n 'file:/path/to/file' | hexud"
  }
  #fetch user input
  ([ -z "$zHEXUDWAITINDEF" ] || [ "$zHEXUDWAITINDEF" = 0 ]) && {
    export zFOXT=3
  } || {
    unset zFOXT
    unset zHEXUDWAITINDEF
  }
  HEXUDIN="$(fox)"
  HEXUDINTEST=${HEXUDIN: 5}
  [ "$HEXUDINTEST" = "error" ] && {
    [ -z "$@" ] && {
      hexud_fail
      return 1
    } || {
      HEXUDIN="$@"
      isfile "$HEXUDIN" && {
        HEXUDIN="$(fox-fr "$HEXUDIN")"
      }
    }
  } || [ "$HEXUDINTEST" = 'file:' ] && {
    HEXUDIN=${HEXUDIN:5}
    isfile "$HEXUDIN" && {
      HEXUDIN="$(fox-fr "$HEXUDIN")"
    } || {
      hexud_fail
      return 1
    }
  }
  #perform hexdump reversal
  while IFS= noglob read -r -k2 -d '' -u0 HEXUDOUT; do
    print -n "\x"$HEXUDOUT""
  done < <(noglob printf '%s' "$HEXUDIN")
  return 0
}
