#!/usr/bin/env zsh
hexudlf() {
  #load modules
  autoload fox
  autoload fox-fr
  autoload isfile
  autoload nrandom
  autoload zmkfifo
  zmodload zsh/files
  #failure printout
  hexudlf_fail() {
    print "Usage: print -n <hex> | hexudlf"
    print "       hexudlf <hex>"
    print "       hexudlf /path/to/file"
    print "       print -n 'file:/path/to/file' | hexudlf"
  }
  #fetch user input
  ([ -z "$zHEXUDLFWAITINDEF" ] || [ "$zHEXUDLFWAITINDEF" = 0 ]) && {
    while IFS= noglob read -r -k5 -t3 -d '' -u0 HEXUDLFINREAD5; do
      HEXUDLFIN="$HEXUDLFINREAD5"
      break
    done
  } || {
    while IFS= noglob read -r -k5 -d '' -u0 HEXUDLFINREAD5; do
      HEXUDLFIN="$HEXUDLFINREAD5"
      break
    done
  }
  [ -z "$HEXUDLFIN" ] && {
    [ -z "$@" ] && {
      hexudlf_fail
      return 1
    } || {
      HEXUDLFIN="$@"
      isfile "$HEXUDLFIN" && {
        fox-fr "$HEXUDLFIN" | hexudlf
        return $?
      }
    }
  } || [ "$HEXUDLFIN" = 'file:' ] && {
    HEXUDLFIN=""$(fox)""
    isfile "$HEXUDLFIN" && {
      fox-fr "$HEXUDLFIN" | hexudlf
      return $?
    } || {
      hexudlf_fail
      return 1
    }
  }
  #fifo setup
  HEXUDLFFIFO="$(nrandom)" &> /dev/null
  HEXUDLFFIFO2="$(nrandom)" &> /dev/null
  [ -d "/tmp" ] && {
    HEXUDLFDIR="/tmp/.libmisc"$UID""
  } || {
    HEXUDLFDIR=""$HOME"/.libmisc"
  }
  ! isfile "$HEXUDLFDIR" && {
    mkdir "$HEXUDLFDIR"
  }
  zmkfifo "$HEXUDLFDIR/$HEXUDLFFIFO"
  zmkfifo "$HEXUDLFDIR/$HEXUDLFFIFO2"
  fox > "$HEXUDLFDIR/$HEXUDLFFIFO2" &|
  (IFS= noglob print -rn "$HEXUDLFIN" && fox-fr "$HEXUDLFDIR/$HEXUDLFFIFO2") > "$HEXUDLFDIR/$HEXUDLFFIFO" &|
  #perform hexdump reversal
  while IFS= noglob read -r -k2 -d '' -u0 HEXUDLFOUT; do
    print -n "\x"$HEXUDLFOUT""
  done < <(fox-fr "$HEXUDLFDIR/$HEXUDLFFIFO")
  rm -rf "$HEXUDLFDIR/$HEXUDLFFIFO"
  rm -rf "$HEXUDLFDIR/$HEXUDLFFIFO2"
  return 0
}
