#!/usr/bin/env zsh
isevennum() {
  autoload chkvldint
  autoload revstr
  NUM="$@"
  if [ -z "$NUM" ]; then
    read -u0 NUM
    if [ -z "$NUM" ]; then
      return 2
    fi
  fi
  if ! chkvldint $NUM; then
    return 3
  fi
  NUMB=$(revstr $NUM)
  NUM=${NUMB: :1}
  case $NUM in
    (1) return 1 ;;
    (3) return 1 ;;
    (5) return 1 ;;
    (7) return 1 ;;
    (9) return 1 ;;
    (*) return 0 ;;
  esac
}
