#!/usr/bin/env zsh

pwr_of() {
  op_one="$1"
  op_two="$2"
  ([ -z "$op_one" ] || [ -z "$op_two" ]) && \
    print "Error: pwr_of received insufficient input!" && \
    return 1
  result="$op_one"
  pwr_count=0
  until [ $pwr_count = $((op_two-1)) ]; do
    result=$((result*op_one))
    pwr_count=$((pwr_count+1))
  done
  print "$result"
  return 0
}
