#!/usr/bin/env zsh
revstr() {
  zREVSTR="$@"
  unset zREVSTROUT
  while IFS= noglob read -r -k1 -d '' -u0 char; do
    zREVSTROUT=""$char""$zREVSTROUT""
  done < <(IFS= noglob print -rn "$zREVSTR")
  IFS= noglob print -rn "$zREVSTROUT"
  return 0
}
