#!/usr/bin/env zsh

rzls() {
  ## load modules
  autoload findlibmisc

  ## find libmisc
  libmiscdir=$(findlibmisc)

  ## execute zls as root
  sudo zsh <<EOF
  fpath=($libmiscdir $fpath)
  autoload zls
  zls $=@
EOF
}
