#!/usr/bin/env zsh
ztput() {
#  jsdk=8
  autoload getstrln
  reset() {
    printf "%s""\e[0m"
#    printf "%s""\033[${jsdk}D"
  }
  bold() {
    printf "%s""\e[1m"
#    printf "%s""\033[${jsdk}D"
  }
  dim() {
    printf "%s""\e[2m"
#    printf "%s""\033[${jsdk}D"
  }
  cvwoah=11
  cvvis() {
    printf "%s""\033[?25h"
#    printf "%s""\033[${cvwoah}D"
  }
  civis() {
    printf "%s""\033[?25l"
#    printf "%s""\033[${cvwoah}D"
  }
  if [ "$1" = "reset" ]; then
    reset
    return 0
  elif [ "$1" = "bold" ]; then
    bold
    return 0
  elif [ "$1" = "dim" ]; then
    dim
    return 0
  elif [ "$1" = "cvvis" ]; then
    cvvis
    return 0
  elif [ "$1" = "civis" ]; then
    civis
    return 0
  fi
  colour_code=${1[1]}
  if [ "$colour_code" = "setaf" ] || [ "$colour_code" = "setab" ]; then
    colour_code=${2[1]}
  fi
  if (( colour_code < 0 || colour_code > 255 )); then
    if [ "$LIBMISCDEBUG" = 1 ]; then
      noglob printf "%s""$colour_code"
    fi
    return 0
  else
#    PHG=$((getstrln printf "%s""\e[3${colour_code}m"))
#    PHK=$((PHG+3))
#    PHJ=$(getstrln $colour_code)
#    PHK=$((PHK+PHJ))
    printf "%s""\e[3${colour_code}m"
#    printf "%s""\033[${PHK}D"
  fi
}
