#!/usr/bin/env zsh

zwhich() {
  ## fetch args
  unset which_arg_array
  declare -a which_arg_array
  for which_args in $=@; do
    which_arg_array+=("$which_args")
  done
  ## env setup
  unset which_match
  which_found_match=0
  which_found_any_match=0
  which_preserve_current_dir=$(pwd)
  IFS=$':'
  ## main loop
  # allow for multiple arguments in one command
  for each_arg in $=which_arg_array; do
    #check each directory in $PATH
    for exec_path in $=PATH; do
      cd $exec_path
      #ensure directory not empty
      if (print *) &> /dev/null; then
        #check each file in directory for match
        for find_executables in *; do
          #if match is found, isn't a directory, and has execute permissions
          if [ "$find_executables" = "$each_arg" ] && [ ! -d "$find_executables" ] && [ -x "$find_executables" ]; then
            which_found_match=1
            which_match=""$exec_path"/"$each_arg""
            break
          else
            which_found_match=0
          fi
        done
        #print results if match found, reset env for next arg, set global return to success
        if [ "$which_found_match" = "1" ]; then
          print $which_match
          unset which_match
          which_found_match=0
          which_found_any_match=1
          break
        fi
      else
        #set match found to 0 if directory empty
        which_found_match=0
      fi
    done
  done
  ##cleanup
  unset IFS
  cd $which_preserve_current_dir
  ##return
  [ "$which_found_any_match" = 1 ] && return 0
  [ "$which_found_any_match" = 0 ] && return 1
}
