#!/usr/bin/env zsh
zzsh() {
  autoload libmiscinit
  libmiscinit
  autoload zstat
  autoload ctext
  autoload ztput
  autoload isfile
  autoload fox-fr
  if [ -z "$USER" ]; then
    USER=unknown
  fi
  if [ -z "$HOSTNAME" ]; then
    if isfile /etc/hostname &> /dev/null; then
      HOSTNAME="$(fox-fr /etc/hostname)"
    else
      HOSTNAME=localhost
    fi
  fi
  zzsh_newlines() {
    print; print; print; print; print; print; print; print; print; print
  }
  while true; do
    [ -z "$zzsh_return_val" ] && zzsh_return_val=0
    print -n ""$(ztput bold)""$(ctext blue)""$USER""$(ztput dim)""$(ctext magenta)"@""$(ctext reset)"$(ztput bold)""$(ctext blue)""$HOSTNAME" "$(ctext reset)""$(ztput dim)""$(ctext cyan)""$(print -n "$(pwd)")" "$(if [ $zzsh_return_val = 0 ]; then ctext green; else ctext reset; ctext red; fi)"> "$(ctext reset)""
    ZZSH=$(read -e " ")
    if [ ! -z "$ZZSH" ]; then
      if [ "$ZZSH" = 'clear' ]; then
        zzsh_newline_spammer=150
        until [ "$zzsh_newline_spammer" = 0 ]; do
          zzsh_newlines; zzsh_newlines; zzsh_newlines; zzsh_newlines; zzsh_newlines; zzsh_newlines; zzsh_newlines; zzsh_newlines; zzsh_newlines; zzsh_newlines
          zzsh_newline_spammer=$((zzsh_newline_spammer-10))
        done
        zzsh_return_val=0
      else
        eval $ZZSH; zzsh_return_val=$?
      fi
    fi
  done
  return 0
}
